
import {
  File,
  LayoutDashboard,
  Users,
  Cog,
  Bell,
  HelpCircle,
  Settings,
  User,
  Home,
  Plus,
  Edit,
  Trash2,
  EyeOff,
  Save,
  X,
  Check,
  AlertTriangle,
  AlertCircle,
  Info,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  Search,
  Download,
  Upload,
  Share2,
  ExternalLink,
  Copy,
  Move,
  Maximize2,
  Minimize2,
  RefreshCw,
  RotateCw,
  RotateCcw,
  ZoomIn,
  ZoomOut,
  Lock,
  Unlock,
  UserPlus,
  UserMinus,
  LogIn,
  LogOut,
  UserCheck,
  UserX,
  Mail,
  MessageSquare,
  Calendar,
  Clock,
  MapPin,
  Phone,
  Link,
  Tag,
  ShoppingCart,
  CreditCard,
  Bookmark,
  Heart,
  Star,
  Flag,
  Award,
  List,
  Grid,
  CheckSquare,
  Radio,
  Sliders,
  Filter,
  Menu,
  BarChart,
  PieChart,
  LineChart,
  AreaChart,
  TrendingUp,
  TrendingDown,
  ListOrdered,
  Code,
  Terminal,
  GitBranch,
  GitCommit,
  GitPullRequest,
  Github,
  Twitter,
  Facebook,
  Instagram,
  Youtube,
  Dribbble,
  Linkedin,
  Globe2,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  CloudSnow,
  CloudLightning,
  Wifi,
  Bluetooth,
  Battery,
  Activity,
  Disc,
  Headphones,
  Camera,
  Video,
  Image,
  Paperclip,
  AtSign,
  Hash,
  Mic,
  Volume1,
  Volume2,
  VolumeX,
  Speaker,
  Tv,
  Monitor,
  Printer,
  MousePointer,
  Keyboard,
  Command,
  Shield,
  Cpu,
  Server,
  AlertOctagon,
  Zap,
  Hammer,
  Book,
  BookOpen,
  Briefcase,
  Cast,
  Key,
  Compass,
  Map,
  Navigation2,
  Droplet,
  Layout,
  LayoutList,
  LayoutTemplate,
  Columns,
  GitMerge,
  Archive,
  Mailbox,
  Inbox,
  Send,
  Clipboard,
  FileText,
  FilePlus,
  FileMinus,
  Folder,
  FolderPlus,
  FolderMinus,
  Layers,
  Package,
  Database,
  SlidersHorizontal,
  Eye,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";

import React from "react";
import { IconOption } from "../types";
import { IconCategory, CategorizedIconOptions, iconCategoryMap } from "../constants/icon-categories";

// Define all available icons
export const iconOptions: IconOption[] = [
  { name: "File", icon: File },
  { name: "LayoutDashboard", icon: LayoutDashboard },
  { name: "Users", icon: Users },
  { name: "Cog", icon: Cog },
  { name: "Bell", icon: Bell },
  { name: "HelpCircle", icon: HelpCircle },
  { name: "Settings", icon: Settings },
  { name: "User", icon: User },
  { name: "Home", icon: Home },
  { name: "Plus", icon: Plus },
  { name: "Edit", icon: Edit },
  { name: "Trash2", icon: Trash2 },
  { name: "Eye", icon: Eye },
  { name: "EyeOff", icon: EyeOff },
  { name: "Save", icon: Save },
  { name: "X", icon: X },
  { name: "Check", icon: Check },
  { name: "AlertTriangle", icon: AlertTriangle },
  { name: "AlertCircle", icon: AlertCircle },
  { name: "Info", icon: Info },
  { name: "ArrowRight", icon: ArrowRight },
  { name: "ArrowLeft", icon: ArrowLeft },
  { name: "ArrowUp", icon: ArrowUp },
  { name: "ArrowDown", icon: ArrowDown },
  { name: "Search", icon: Search },
  { name: "Download", icon: Download },
  { name: "Upload", icon: Upload },
  { name: "Share2", icon: Share2 },
  { name: "ExternalLink", icon: ExternalLink },
  { name: "Copy", icon: Copy },
  { name: "Move", icon: Move },
  { name: "Maximize2", icon: Maximize2 },
  { name: "Minimize2", icon: Minimize2 },
  { name: "RefreshCw", icon: RefreshCw },
  { name: "RotateCw", icon: RotateCw },
  { name: "RotateCcw", icon: RotateCcw },
  { name: "ZoomIn", icon: ZoomIn },
  { name: "ZoomOut", icon: ZoomOut },
  { name: "Lock", icon: Lock },
  { name: "Unlock", icon: Unlock },
  { name: "UserPlus", icon: UserPlus },
  { name: "UserMinus", icon: UserMinus },
  { name: "LogIn", icon: LogIn },
  { name: "LogOut", icon: LogOut },
  { name: "UserCheck", icon: UserCheck },
  { name: "UserX", icon: UserX },
  { name: "Mail", icon: Mail },
  { name: "MessageSquare", icon: MessageSquare },
  { name: "Calendar", icon: Calendar },
  { name: "Clock", icon: Clock },
  { name: "MapPin", icon: MapPin },
  { name: "Phone", icon: Phone },
  { name: "Link", icon: Link },
  { name: "Tag", icon: Tag },
  { name: "ShoppingCart", icon: ShoppingCart },
  { name: "CreditCard", icon: CreditCard },
  { name: "Bookmark", icon: Bookmark },
  { name: "Heart", icon: Heart },
  { name: "Star", icon: Star },
  { name: "Flag", icon: Flag },
  { name: "Award", icon: Award },
  { name: "List", icon: List },
  { name: "Grid", icon: Grid },
  { name: "CheckSquare", icon: CheckSquare },
  { name: "Radio", icon: Radio },
  { name: "Sliders", icon: Sliders },
  { name: "Filter", icon: Filter },
  { name: "Menu", icon: Menu },
  { name: "BarChart", icon: BarChart },
  { name: "PieChart", icon: PieChart },
  { name: "LineChart", icon: LineChart },
  { name: "AreaChart", icon: AreaChart },
  { name: "TrendingUp", icon: TrendingUp },
  { name: "TrendingDown", icon: TrendingDown },
  { name: "ListOrdered", icon: ListOrdered },
  { name: "Code", icon: Code },
  { name: "Terminal", icon: Terminal },
  { name: "GitBranch", icon: GitBranch },
  { name: "GitCommit", icon: GitCommit },
  { name: "GitPullRequest", icon: GitPullRequest },
  { name: "Github", icon: Github },
  { name: "Twitter", icon: Twitter },
  { name: "Facebook", icon: Facebook },
  { name: "Instagram", icon: Instagram },
  { name: "Youtube", icon: Youtube },
  { name: "Dribbble", icon: Dribbble },
  { name: "Linkedin", icon: Linkedin },
  { name: "Globe2", icon: Globe2 },
  { name: "Sun", icon: Sun },
  { name: "Moon", icon: Moon },
  { name: "Cloud", icon: Cloud },
  { name: "CloudRain", icon: CloudRain },
  { name: "CloudSnow", icon: CloudSnow },
  { name: "CloudLightning", icon: CloudLightning },
  { name: "Wifi", icon: Wifi },
  { name: "Bluetooth", icon: Bluetooth },
  { name: "Battery", icon: Battery },
  { name: "Activity", icon: Activity },
  { name: "Disc", icon: Disc },
  { name: "Headphones", icon: Headphones },
  { name: "Camera", icon: Camera },
  { name: "Video", icon: Video },
  { name: "Image", icon: Image },
  { name: "Paperclip", icon: Paperclip },
  { name: "AtSign", icon: AtSign },
  { name: "Hash", icon: Hash },
  { name: "Mic", icon: Mic },
  { name: "Volume1", icon: Volume1 },
  { name: "Volume2", icon: Volume2 },
  { name: "VolumeX", icon: VolumeX },
  { name: "Speaker", icon: Speaker },
  { name: "Tv", icon: Tv },
  { name: "Monitor", icon: Monitor },
  { name: "Printer", icon: Printer },
  { name: "MousePointer", icon: MousePointer },
  { name: "Keyboard", icon: Keyboard },
  { name: "Command", icon: Command },
  { name: "Shield", icon: Shield },
  { name: "Cpu", icon: Cpu },
  { name: "Server", icon: Server },
  { name: "AlertOctagon", icon: AlertOctagon },
  { name: "Zap", icon: Zap },
  { name: "Hammer", icon: Hammer },
  { name: "Book", icon: Book },
  { name: "BookOpen", icon: BookOpen },
  { name: "Briefcase", icon: Briefcase },
  { name: "Cast", icon: Cast },
  { name: "Key", icon: Key },
  { name: "Compass", icon: Compass },
  { name: "Map", icon: Map },
  { name: "Navigation2", icon: Navigation2 },
  { name: "Droplet", icon: Droplet },
  { name: "Layout", icon: Layout },
  { name: "LayoutList", icon: LayoutList },
  { name: "LayoutTemplate", icon: LayoutTemplate },
  { name: "Columns", icon: Columns },
  { name: "GitMerge", icon: GitMerge },
  { name: "Archive", icon: Archive },
  { name: "Mailbox", icon: Mailbox },
  { name: "Inbox", icon: Inbox },
  { name: "Send", icon: Send },
  { name: "Clipboard", icon: Clipboard },
  { name: "FileText", icon: FileText },
  { name: "FilePlus", icon: FilePlus },
  { name: "FileMinus", icon: FileMinus },
  { name: "Folder", icon: Folder },
  { name: "FolderPlus", icon: FolderPlus },
  { name: "FolderMinus", icon: FolderMinus },
  { name: "Layers", icon: Layers },
  { name: "Package", icon: Package },
  { name: "Database", icon: Database },
  { name: "SlidersHorizontal", icon: SlidersHorizontal },
];

// Organize icons by category
export const categorizedIconOptions: CategorizedIconOptions[] = Object.entries(iconCategoryMap).map(
  ([category, iconNames]) => {
    const icons = iconNames
      .map(name => iconOptions.find(option => option.name === name))
      .filter(Boolean) as IconOption[];
    
    return {
      category: category as IconCategory,
      icons
    };
  }
);

// Utility function to get an icon by name
export const getIconByName = (name: string): LucideIcon | undefined => {
  const option = iconOptions.find((option) => option.name === name);
  return option?.icon;
};

// Utility function to render an icon by name
export const renderIcon = (name: string | undefined, props?: LucideProps): React.ReactNode => {
  if (!name) return null;
  const icon = getIconByName(name);
  if (!icon) return null;
  return React.createElement(icon, { className: "h-4 w-4", ...props });
};

// Get icons by a specific category
export const getIconsByCategory = (category: IconCategory): IconOption[] => {
  const categoryData = categorizedIconOptions.find(c => c.category === category);
  return categoryData?.icons || [];
};
