// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihzedshfshpgxzatlbpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImloemVkc2hmc2hwZ3h6YXRsYnBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MjA2NjQsImV4cCI6MjA1NzE5NjY2NH0.P6a_WA_IOauwRGlAVdekQBAKjbzb8WWESIWnyDmoIfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);